listening-port=3478
tls-listening-port=5349
external-ip=91.98.141.188
realm=theeverywhereoffice.nomadworkmates.com
lt-cred-mech
user=workadventure:3f7b355340e5b32e61d1d887aa2adcc298221cab60351a20
no-multicast-peers
